project_name: "kube-adguard-ing"
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
    binary: "{{ .ProjectName }}"
    main: "./"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
dockers:
- image_templates:
    - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
  use: buildx
  goarch: amd64
  dockerfile: docker/Dockerfile
  build_flag_templates:
    - "--platform=linux/amd64"
- image_templates:
    - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: docker/Dockerfile
  build_flag_templates:
    - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
release:
  extra_files:
    - glob: build/kustomize.tar.gz
    - glob: build/kube-adguard-ing.yaml
  footer: |
    ## Docker images
    
        ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}
    
    Both images supports `arm64` and `amd64`
    
    * base image built on top of `scratch`
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'