---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adguard-ingress
  labels:
    app: adguard-ingress
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adguard-ingress
  labels:
    app: adguard-ingress
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adguard-ingress
  labels:
    app: adguard-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adguard-ingress
subjects:
  - kind: ServiceAccount
    name: adguard-ingress
    namespace: adguard-ingress