# The universal pipeline which uses Makefile for build and release
name: Build and release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.22'
        id: go

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Pull tag
        run: git fetch --tags

      - name: Install kustomize
        run: |
          mkdir -p build
          cd build
          curl -L -s "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz"  | \
            tar -xzvf -

      - name: Update tags in manifests
        run: |
          # copy manifests
          cp -rv deployment build/
          
          yq -i ".images[].newTag = \"${GITHUB_REF_NAME/#v}\"" build/deployment/kustomize/kustomization.yaml
          ./build/kustomize build build/deployment/kustomize > build/kube-adguard-ing.yaml
          tar -czvf build/kustomize.tar.gz -C build/deployment/kustomize/ .

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
